name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

   # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Sepecify POM file
      run: mvn -f $GITHUB_WORKSPACE/PokemonFramework/pom.xml clean install  # Specify the POM file directly

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven Surefire
      run: mvn test

    - name: Run JaCoCo coverage report
      run: mvn jacoco:report

    - name: Upload JaCoCo Coverage Report to GitHub
      uses: codecov/codecov-action@v2
      with:
        file: './target/site/jacoco/jacoco.xml'  # Path to your JaCoCo report
