name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}/PokemonFramework  # Set default working directory here

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up JDK 23
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'

    # Cache Maven dependencies
    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install

    - name: Run tests with Maven Surefire
      run: mvn test

    - name: Run JaCoCo coverage report
      run: mvn jacoco:report

    - name: Upload JaCoCo Coverage Report to GitHub
      uses: codecov/codecov-action@v2
      with:
        file: './target/site/jacoco/jacoco.xml'  # Path to your JaCoCo report

    # Upload Jacoco HTML report as artifact
    - name: Upload Jacoco report as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: ${{ github.workspace }}/PokemonFramework/target/site/jacoco/

    # Upload Jacoco coverage data to Coveralls
    - name: Upload Jacoco coverage data to Coveralls
      uses: coverallsapp/github-action@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
   
    # Deploy to github pages
    - name: Deploy to Maven Repository
      run: mvn deploy -DskipExisting=true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}